In [ ]:
import numpy as np

**1. Задати вектор що складається з перших п'яти натуральних чисел**

In [ ]:
vector = np.array([1, 2, 3, 4, 5])

vector


array([1, 2, 3, 4, 5])

**2. Транспонувати вектор**

In [ ]:
v1 = np.matrix([1, 2, 3, 4, 5])
print(v1)
v2=v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

**3. Напишіть функцію, яка переверає вектор у зворотьтньому порядку**

In [ ]:
v = np.array([1, 2, 3, 4, 5])
print(v[::1])

[1 2 3 4 5]


In [ ]:
v = np.flip(v)
print(v)

[5 4 3 2 1]


**4. Обчислити середнє значення вектора**

In [ ]:
print(np.mean(v))

3.0


**5. Знайти найбільший і найменьшй елемент вектора**

In [ ]:
print(np.max(v))
print(np.min(v))

5
1


**6. Обчислити скалчрний добуток двох векторів**

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
dot1 = np.dot(v1, v2)
print("Скалярний добуток:", dot1)


Скалярний добуток: 32


**7. Напишыть функцію, яка нормалізує вектор**

In [ ]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print (norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

**8. Задайте вектори. Визначте, чи є вони ортогональними. Підказка: якщ скалрний добуток дорівнює 0, вектори ортогональні**

In [ ]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
np.dot(v1, v2)

np.int64(0)

np.int64(0)

**9. Визначити унікальніц елементи вектора**

In [ ]:
v = np.array([1, 2, 3, 2, 4, 5, 3])
np.unique(v)


array([1, 2, 3, 4, 5])

**10. Знайдли ветори**

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1-v2)
print(v2-v1)
print(v1+v2)
print(v1+v2)
print(v1*v2)
print(v2*v1)
print(v1/v2)
print(v2/v1)



[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


**11. перевірити чи довжиина ветора дорівнює 5**

In [ ]:
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)
np.isclose(length, 5)

np.False_

**12. Задати Матирю, заповнену випадковими числами**

In [ ]:
a = np.random.randint(0, 11, (3, 3))
a

array([[8, 5, 7],
       [6, 2, 8],
       [8, 0, 4]])

**13. Обчислити визначник матриці**

In [ ]:
np.linalg.det(a)


np.float64(151.9999999999999)

**14. Знаходження оберненої матриці**

In [ ]:
np.linalg.inv(a)

array([[ 0.05263158, -0.13157895,  0.17105263],
       [ 0.26315789, -0.15789474, -0.14473684],
       [-0.10526316,  0.26315789, -0.09210526]])

15. Розв'яжіть систему лінійних рівнянь А*х = b, де А- матриця коефіціентів, b - вектор вільн х чисел **текст жирним шрифтом**

In [ ]:
aq = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[ 0.55263158  0.26315789 -0.10526316]
[ 0.55263158  0.26315789 -0.10526316]


**16. Множення двох матриць**

In [ ]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
h = np.array([5, 3, 4])
print("Множення матриць:\n", np.dot(a, h))

Множення матриць:
 [-2 -6 16]


In [ ]:
a = np.matrix([[1, 3, -4], [0, 2, -3]])
h = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[5 3 4]
[[-2 -6]]


**17. Транспонуванн матриці**

In [ ]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[5 3 4]


In [ ]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[5 3 4]


**18. Перевірка симетричності матриці**

In [ ]:
matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
np. allclose(matrix, matrix.T)


True

**19. Обчислення сліду матриці**

In [ ]:
np.trace(matrix)

np.int64(6)

**20. Дії матриць**

In [ ]:
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**21. піднесення матриці до ступеня**

In [ ]:
a = np.matrix([[1, 2], [3, 4]])
np.linalg.matrix_power(a, 2)


matrix([[ 7, 10],
        [15, 22]])

**22.Сортування рядків або стовпців матриці**

In [ ]:
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])

print(b)
print(np.sort(b, axis = 0))
print(np.sort(b, axis = 1))
print(np.sort(b, axis = None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [ ]:
a = np.array([[1, 4], [3, 1]])
print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [ ]:
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


**23. Підрахувати суму елементів коожного рядка матриці. Відповідь запиши, Як вектор-стовпчики**

In [ ]:
row_sums = np.sum(a, axis=1).reshape(-1,1)
print("Сума елементів кожного рядка: ")
print(row_sums)

Сума елементів кожного рядка: 
[[5]
 [4]]
